name: Unit Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.22']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Run library go tests
        run: cd directdebit; go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...
